language: python - "3.6"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - "./miniconda.sh -b"
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes python=3.6 numpy scipy scikit-image scikit-learn matplotlib sympy h5py mpi4py
  - pip install loompy
  - pip install ruamel.yaml
  - pip install dask
  - pip install dask.distributed
  - pip install nd2reader==2.1.3
  - git clone https://github.com/linnarsson-lab/pysmFISH.git
  - cd velocyto.py; pip install .;cd ..
  - git clone https://github.com/sphinx-doc/sphinx.git
  - cd sphinx; pip install .;cd ..
